services:
  _defaults:
    autowire: true
    autoconfigure: true

  AcquiringBundle\:
    resource: '../src/'
    exclude:
      - '../../Infrastructure/DependencyInjection/'
      - '../../Entity/'
