old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    contract_created:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.contract_created', type: direct }
    notify_person:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.notify_person', type: direct }

  consumers:
    contract_created:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.contract_created', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.contract_created' }
      callback: App\Billing\Presentation\Amqp\Consumer\ContractCreated\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    notify_person:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.notify_person', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.notify_person' }
      callback: NotifierBundle\src\Presentation\Ampq\Consumer\SendEmailNotification\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
