security:
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_MUSICIAN_MANAGER
            - ROLE_TARIFF_MANAGER
            - ROLE_ACCOUNT_MANAGER
        ROLE_TARIFF_MANAGER:
            - ROLE_ACCOUNT_MANAGER
            - ROLE_MUSICIAN_MANAGER
        ROLE_MUSICIAN_MANAGER:
            - ROLE_VIEWER
            - ROLE_USER
        ROLE_ACCOUNT_MANAGER:
            - ROLE_VIEWER
            - ROLE_USER

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        employee_user_provider:
            entity:
                class: App\Person\Domain\Entity\Employee
                property: login
    firewalls:
        dev:
            pattern:
                - ^/(_profiler|wdt)/
                - ^/css/
                - ^/images/
                - ^/js/
                - ^/api/person/v1/employee/login$
                - ^/api/v1/probe/
            security: false
        main:
            lazy: true
            provider: employee_user_provider
            stateless: true
            custom_authenticator: App\Core\Security\Authenticator\JWTTokenAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/api/person/v1/employee/, methods: [POST, DELETE], roles: [ROLE_ADMIN] }
        - { path: ^/api/person/v1/musician/, methods: [POST, PATCH, PUT, DELETE], roles: [ROLE_MUSICIAN_MANAGER] }
        - { path: ^/api/person/v1/musician/, methods: [GET], roles: [ROLE_VIEWER] }
        - { path: ^/api/billing/v1/contract/, methods: [POST], roles: [ROLE_ACCOUNT_MANAGER] }
        - { path: ^/api/billing/v1/contract/, methods: [GET], roles: [ROLE_VIEWER] }
        - { path: ^/api/billing/v1/tariff/, methods: [POST, PUT], roles: [ROLE_TARIFF_MANAGER] }
        - { path: ^/api/billing/v1/tariff/, methods: [GET], roles: [ROLE_VIEWER] }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
