version: '3.7'

services:

  php-fpm:
    build: docker
    container_name: 'primeira-php'
    ports:
      - '9001:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'primeira-nginx'
    working_dir: /app
    ports:
      - '77:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    ports:
      - 25432:5432
    container_name: 'primeira-postgresql'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'primeira'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - primeira_dump:/app/dump
      - primeira_postgresql:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    ports:
      - 35432:5432
    container_name: 'primeira_postgresql_test'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'primeira'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - primeira_dump:/app/dump
      - primeira_postgresql_test:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7.5-management
    working_dir: /app
    hostname: primeira-rabbit-mq
    container_name: 'primeira-rabbit-mq'
    ports:
      - '35672:15672'
      - '25672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  primeira_dump:
  primeira_postgresql:
  primeira_postgresql_test:
