services:
  _defaults:
    autowire: true
    autoconfigure: true

  NotifierBundle\:
    resource: '../src/'
    exclude:
      - '../../Infrastructure/DependencyInjection/'
      - '../../Domain/Entity/'
