probes:
    resource:
        path: ../src/System/Presentation/Http/Rest/V1/Controller/
        namespace: App\System\Presentation\Http\Rest\V1\Controller
    type: attribute

person:
    resource:
        path: ../src/Person/Presentation/Http/Rest/
        namespace: App\Person\Presentation\Http\Rest
    type: attribute

billing:
    resource:
        path: ../src/Billing/Presentation/Http/Rest/V1/Controller/
        namespace: App\Billing\Presentation\Http\Rest\V1\Controller
    type: attribute
